# More documentation about how to customize your build
# can be found here:
# https://docs.fastlane.tools
fastlane_version "1.109.0"

build_number = DateTime.now.strftime('%Y%m%d%H%M')
UI.important "Build Number : " + build_number

lane :release do
  # add_git_tag(
  #   grouping: 'fastlane-builds',
  #   prefix: 'v',
  #   build_number: build_number
  # )
  # push_git_tags

  iosRelease
  androidRelease
end

lane :iosRelease do
  sh 'cd ../ && react-native bundle --platform ios --dev false --entry-file index.ios.js --bundle-output ./ios/main.jsbundle --assets-dest ./ios'

  cocoapods(
    podfile: './ios/Podfile'
  )

  increment_build_number({
    build_number: build_number,
    xcodeproj: './ios/FlagQuiz.xcodeproj'
  })

  gym(
    scheme: "FlagQuiz",
    export_method: "app-store",
    workspace: './ios/FlagQuiz.xcworkspace',
    output_directory: "build"
  )

  pilot(
    skip_waiting_for_build_processing: true,
    team_id: "N748PGRLNM"
  )
end

lane :androidRelease do
  gradle(
    task: 'clean',
    project_dir: "android/"
  )
  gradle(
    project_dir: "android",
    task: "assembleRelease",
    properties: {
      'versionCode' => build_number
    }
  )
  supply(
    track: "alpha",
    json_key: "android/keystores/google-play-service.json",
    package_name: "com.alenoir.flagcontest",
    apk: "android/app/build/outputs/apk/app-release.apk"
  )
end
